### ISSUE TITLE
Option to correct the full-text link is needed

### ISSUE THREAD

**Issue by ikashnitsky** [Impactstory/impactstory-tng#16]
It is strange that once you provided an open access link it is impossible to change it. 
There are numerous reasons why one may want the readers to grab the full text from one of the specific sources.

**Comment by peterdesmet** [comment]
I agree 😌  one of my publications has a wrong link I'd like to update.

**Comment by peterdesmet** [comment]
Oops, made that mistake again and cannot correct. 😬

**Comment by Kevin-Mattheus-Moerman** [comment]
This is a really annoying "bug". I love ImpactStory but it is sad broken links cannot be fixed. Are there any updates on this? @hpiwowar @jasonpriem any chance this is easy to fix? If you do not intend to work on this could you point us in the right direction as to where in "the code" one would work on fixing this issue? Thanks!

**Comment by jasonpriem** [comment]
Good question, Kevin. The current status is that we don't have any funding for Impactstory, and we don't charge for it. That means it costs us money to run and maintain. We're a small organization and don't have a lot of money to spare, unfortunately. 

This particular issue does not affect many users (although you are absolutely right it's super annoying for those it does affect). So I'm very sorry to say it's probably not going to be fixed any time soon. Which I HATE to say, but it's currently the reality we're working with.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks for your reply. I understand what you are saying. 

However, are you open to others helping to fix this issue, like free helpers from the open source community, i.e. people like me :smile: ?
If you agree this issue should be addressed perhaps you could reopen it and we could try to attract help. If you are open to this it would be great if you could point people in the right direction. Like perhaps you could mention which codes control the "add link to full text parts". I could try to study these and try to add an "Update full text link" feature. If you want to leave this for now and wait until you have funding that is fine too but the beauty of open source and on-line volunteers is that work can continue right?

**Comment by peterdesmet** [comment]
+1 Not sure I can contribute much to the code, but happy to test it. In any case, would be nice to have this issue still listed as open.

**Comment by agitter** [comment]
@Kevin-Mattheus-Moerman I'm interested in this feature as well.  I don't have time to implement it myself, but I found this code as a starting point if you or others want to attempt it:

https://github.com/Impactstory/impactstory-tng/blob/498981b4746317f66025afe8ed535d51bb014fa5/static/dist/ti.js#L1602-L1620

This is the dialog that appears after clicking this button on a publication page:
![image](https://user-images.githubusercontent.com/3532898/38208973-5efc2d5c-3678-11e8-8990-3aa0d58573fb.png)

Perhaps that button could be replaced with a nearly identical one saying `Update the link to free fulltext` if the full text is set already?

**Comment by HeidiSeibold** [comment]
Hi all,

I would like to add a thought to this issue. The data that we put into Impactstory and that is incorrect sometimes and needs to be corrected, is used for Unpaywall. Could fixing the link issue in that sense be paid through Unpaywall funding? In order to improve data quality of Unpaywall?

Tagging @jasonpriem and @richard-orr as you seem to be the most active contributors of Unpaywall.

Let me know if there is anything I can do to help and fix the issue.

Best,
Heidi
