### ISSUE TITLE
Impactstory in Wikidata

### ISSUE THREAD

**Issue by HeidiSeibold** [Impactstory/impactstory-tng#26]
I am participating in the JROST (http://jrost.org/) mozsprint and want to add open science tools to Wikidata (see issue https://github.com/OpenScienceRoadmap/mozilla-sprint-2018/issues/7). 

I have a question about this:

Is it correct that Impactstory is both a tool and a nonprofit? So actually there should be two entries, one for each, right?
So far there is only an entry for the nonprofit https://www.wikidata.org/wiki/Q16996711.

If you are interested, please do get in touch with JROST :handshake:

**Comment by hpiwowar** [comment]
Yes, that's right.  I know the names are confusing!
Impactstory is the non-profit (http://impactstory.org/) which itself has built many tools (including Depsy, Unpaywall, etc)
and more recently we've been calling the profile tool "Impactstory Profiles" (https://profiles.impactstory.org/)  to distinguish it from the company.  Hope that helps?
