### ISSUE TITLE
Sum of mentions = 0

### ISSUE THREAD

**Issue by peterdesmet** [Impactstory/impactstory-tng#29]
The sum of mentions is erroneously listed as `0` on the [homepage](https://profiles.impactstory.org/u/0000-0002-8442-8025) and [timeline](https://profiles.impactstory.org/u/0000-0002-8442-8025/timeline) of my profile.

**Comment by hpiwowar** [comment]
Fixed!  Sorry about that Peter... one of our data producers changed and it caused a bug.  Thanks for your patience.
