### ISSUE TITLE
Auth with ORCID broken (invalid redirect url)

### ISSUE THREAD

**Issue by VladyslavLishchyna** [Impactstory/impactstory-tng#33]
![image](https://user-images.githubusercontent.com/24877107/209126516-9730f0f9-56f8-4a8b-8b20-105f6d84b887.png)

**Comment by gmerlino** [comment]
Still broken it seems.
News / ETA for bugfix?

**Comment by rempsyc** [comment]
Same on Chrome and Edge: 

![impactstory error](https://user-images.githubusercontent.com/13123390/232095671-8fe20a0a-ea3b-41f1-83b8-5fb7c295557b.png)

**Comment by musoke** [comment]
![image](https://user-images.githubusercontent.com/16665084/233701639-78595b24-389a-466e-b490-ef6da93e944f.png)

still broken on firefox

**Comment by ararebit** [comment]
I am using Firefox on a Mac. I recently updated the email addresses associated with my ORCID.

<img width="473" alt="Screenshot 2023-05-19 at 4 20 39 PM" src="https://github.com/ourresearch/impactstory-tng/assets/1444018/38e83213-5393-4854-a521-0c290e3bccf7">

**Comment by ararebit** [comment]
Same error in Safari.

**Comment by Kevin-Mattheus-Moerman** [comment]
@jasonpriem @hpiwowar :wave: is the impactstory project still maintained?

I get the same as above on the Brave browser. Also, FireFox doesn't even open impactstory pages anymore at all for me.

**Comment by jasonpriem** [comment]
Unfortunately, Impactstory is in a holding pattern for now, as our grant funding ran out for the project some time ago. We'll have more announcements about the future of the Impactstory platform later this summer. But I can say that OpenAlex will be our priority going forward, but thankfully a lot of what Impactstory did, OpenAlex will be able to do soon. I'm very sorry for the inconvenience.
