### ISSUE TITLE
Duplicates in press links

### ISSUE THREAD

**Issue by adammwilson** [Impactstory/impactstory-tng#6]
Sometimes there are duplicates in the press links.  I imagine this will be very hard to solve given they have unique URLs, but perhaps the media source and title should be cross checked?  Or maybe since it's in two places (below on news and blog) it should be counted twice?

for example:

` {
                    "attribution": "Washington Post", 
                    "posted_on": "2016-05-16T11:17:28+00:00", 
                    "source": "news", 
                    "title": "What you can tell about the world just by looking at clouds", 
                    "url": "https://www.washingtonpost.com/news/wonk/wp/2016/05/16/what-you-can-tell-about-the-world-just-by-looking-at-clouds/"
                }, 
                {
                    "attribution": "Washington Post", 
                    "posted_on": "2016-05-16T10:30:11+00:00", 
                    "source": "news", 
                    "title": "What you can tell about the world just by looking at clouds", 
                    "url": "http://www.washingtonpost.com/blogs/wonkblog/wp/2016/05/16/what-you-can-tell-about-the-world-just-by-looking-at-clouds/"
                }, 
 `

**Comment by hpiwowar** [comment]
Thanks for the bug report adam!  Really appreciate you taking the time to submit the bug reports.

In this case I think it doesn't happen very often and as you say it's not simple to solve, so I'm going to close this as a #wontfix for now.  Will keep it in mind though, and reopen if we see it throws off the numbers such that our news stats aren't trustworthy.

thanks again for reporting!!

cheers, 
Heather
